### PR TITLE
Draft: Add CLI template

### PR DESCRIPTION
**Pull request by colinkiama**
This adds a template for CLI Tools.

Provides a basic setup that utilises `OptionContext`, provides a command and a template for defining more commands.

### CODE REVIEW

**Comment by Prince781** [comment]
Interesting idea, but I think I want the CLI template to be improved or at least rationalized with how other open-source projects do things. Is this a pattern you see in other CLI tools (for example, flatpak)?

**Comment by colinkiama** [comment]
Sorry, I made this a while ago, there’s so much I’d change now 😅.

The pattern only partially matches what you would see in existing open-source CLIs.

One of the main changes would be giving each command their own OptionContext.

**Comment by Prince781** [comment]
If you want to close or revise this PR, let me know.

**Comment by colinkiama** [comment]
I would like to revise this PR

**Comment by colinkiama** [comment]
I’d like to close this actually

**Pull request closed without merging**
