### PR TITLE
Add GitHub Action to lint and build Flatpak for `eos` template

### PR DESCRIPTION
**Pull request by dar5hak**
For #9.

This makes a couple of assumptions:
- that the user will use `main` as the default branch
- and they will set up a secret token for GitHub Actions

### CODE REVIEW

**Comment by Prince781** [comment]
Sorry, I'll take a look at this soon. I've been busy the past few weeks. Ping me if I don't respond by Friday.

**Comment by dar5hak** [comment]
Yeah, no hurries. ✌️

**Comment by Prince781** [comment]
"Soon" apparently meant 1.6 years. Sorry about that.

I rebased your branch.

**Comment by dar5hak** [comment]
Ah well, I forgot about this too. I should probably pick up the other items I listed. Thanks! 😄

**Pull request merged**
